### ISSUE TITLE
Under what OS is this actually expected to run?

### ISSUE THREAD

**Issue by bolind** [gojuno/make-profiler#4]
I've spent the better part of an hour getting this to work, with no success. I get unicode errors in io.StringIO, /tmp/ makefiles errors and whatnot. I tried Ubuntu 12, 14, and 16.

**Comment by Komzpa** [comment]
Hi,

It works for us under ubuntu 17.04, 17.10, 18.04, and was running on 16.04. Can you share your case and more precise information on what errors are?

**Comment by Komzpa** [comment]
Hi,

I've checked with internal usage and changed install guide to use `pip3` instead of `pip` to run it. Sorry for inconvenience, hope this helps.

**Comment by bolind** [comment]
Hi, thanks for your reply!

The following Dockerfile illustrates the problem:

    FROM ubuntu:bionic

    RUN apt -y update
    RUN apt -y install --fix-missing
    RUN apt -y install apt-utils
    RUN apt -y install python3-pip
    RUN pip3 install https://github.com/gojuno/make-profiler/archive/master.zip
    RUN echo "all:" > Makefile
    RUN echo "\t@echo bar" >> Makefile
    RUN profile_make
I get the following output:

    Traceback (most recent call last):
      File "/usr/local/bin/profile_make", line 11, in <module>
        load_entry_point('make-profiler==1.0.0', 'console_scripts', 'profile_make')()
      File "/usr/local/lib/python3.6/dist-packages/make_profiler/__main__.py", line 92, in main
        args.svg_filename
      File "/usr/local/lib/python3.6/dist-packages/make_profiler/dot_export.py", line 160, in render_dot
        unflatten = Popen('unflatten', stdin=PIPE, stdout=PIPE)
      File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'unflatten': 'unflatten'

Attempting to execute the test gives the same result.

**Comment by Komzpa** [comment]
Thank you for the patience!

`unflatten` is part of graphviz suite. I've updated Readme, and your Dockerfile works for me if I add this:
```
RUN apt -y install graphviz
```

**Comment by bolind** [comment]
Alright, the test works now! Also needed to install awk/gawk.

The README has a small error: it's python3-pip, not python-pip3.

Thanks!

**Comment by Komzpa** [comment]
Thank you! Fixed. I hope you find this project helpful :)

Oops, this typo exists in our internal provisioning system too, thanks for making Juno better :)

**Comment by bolind** [comment]
I'm happy to be able to help, thanks for making this project!

It's barfing on my Makefile setup, but it's a nasty one, involving recursive make and includes. If I find the time I'll make a small example.

**Comment by Komzpa** [comment]
Includes should work, but they won't be instrumented. We're using them for configuration variables mostly.

Even posting an error message may help :)
