### ISSUE TITLE
Recipe commences before first target. Stop

### ISSUE THREAD

**Issue by Artalus** [gojuno/make-profiler#5]
```
profile_make -f Makefile.arm clean
INFO:make_profiler:make -f /tmp/tmpkloliqkq clean
/tmp/tmpkloliqkq:17: *** recipe commences before first target.  Stop.
```

**Comment by Komzpa** [comment]
@Artalus can you post the makefile you're feeding in?

**Comment by Artalus** [comment]
Unfortunately it is generated by a build system, so it's very messy and has thousands lines of code.
I will see if I can reproduce the problem on one of our lesser projects or something standalone manually created.

**Comment by Komzpa** [comment]
Can't reproduce. Please reopen when you will have more details.

**Comment by Artalus** [comment]
@Komzpa  Nailed it.

`$ cat Makefile `
```Makefile
all: build
export X=1
export Y=2

export Z=3

app.exe: file.o
	gcc -o app.exe file.o
appd.exe: file.o
	gcc -o app.exe file.o

file.o: file.cpp
	gcc -c file.cpp -o file.o


ifdef debug
ifeq ($(debug),1)
build: appd.exe
else
build: app.exe
endif
else
build: appd.exe app.exe
endif
```

`$ profile_make  # OK`
`$ profile_make debug=1`
```
INFO:make_profiler:make -f /tmp/tmpx98txnq1 debug=1
/tmp/tmpx98txnq1:11: *** recipe commences before first target.  Stop.
```

The resulting Makefile: https://hastebin.com/hevipusisa.bash

If I get it right, the formatting gone awry  causes some problems to `make` once it has to build anything but the first target.
